image: docker:19.03.12
services:
    - docker:19.03.12-dind

variables:
  REPO: nexus.farazpardazan.com/request-classification/landing
  VER: $REPO:$CI_COMMIT_TAG


stages:
  - build docker image dev
  - build docker image release

docker build dev:
  stage: build docker image dev
  script:
    - echo "$REGISTRY_PASSWORD" | docker login  https://nexus.farazpardazan.com  -u "$REGISTRY_USER" --password-stdin
    - docker build -t $VER -f Dockerfile .
    - docker push $VER
  rules:
    - if: $CI_COMMIT_TAG =~ /(^[0-9]+.[0-9]+.[0-9]+-DEV)/
      when: always

